replicaCount: 1
revisionHistoryLimit: 1

image:
  registry: herbrandson
  name: k8dash
  tag: latest
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 300Mi

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 30

service:
  name: Node
  type: NodePort
  servicePort: 4654

# If true will create k8dash-sa and associate with cluster-admin role. Secret can be used for auth page with:
# kubectl describe secret k8dash-sa-token-xxxxx
createServiceAccount: false

ingress:
  enabled: false

  ## Kubernetes Dashboard Ingress annotations
  # annotations:
  #   kubernetes.io/ingress.class: nginx

  ## Kubernetes Dashboard Ingress hostnames
  # host: kubernetes-dashboard.domain.com
  paths:
    - /

  ## Kubernetes Dashboard Ingress TLS configuration
  # tls:
  #   - secretName: kubernetes-dashboard-tls
  #     hosts:
  #       - kubernetes-dashboard.domain.com
